// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxG3NumjuFdO17mDztWN-lowi5pmEP7wM',
    appId: '1:232675016348:web:55c20ce0ff2b54781bf759',
    messagingSenderId: '232675016348',
    projectId: 'fikr-project',
    authDomain: 'fikr-project.firebaseapp.com',
    storageBucket: 'fikr-project.firebasestorage.app',
    measurementId: 'G-X7QNHEMB5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNwkLLKLTyU46J1VIkjy0njmzCo-tKsM',
    appId: '1:232675016348:android:6d537e645c6697431bf759',
    messagingSenderId: '232675016348',
    projectId: 'fikr-project',
    storageBucket: 'fikr-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqY8zrDune-QWtOZS3b5UNMSLvC6BitU',
    appId: '1:232675016348:ios:ca9c676443eedc941bf759',
    messagingSenderId: '232675016348',
    projectId: 'fikr-project',
    storageBucket: 'fikr-project.firebasestorage.app',
    iosBundleId: 'com.example.fikr',
  );
}
